# IEE 577: Data Science for Decision System Analytics Spring 2021
## Assignment 1
## Nikhil Joshi - 1219967502

### Problem 1
##### (i) Depth of network: First, please try to complete Table 2.1 by trying on selecting two out of four datasets with different neural networks to test the effect of different number of layers (depth). Please keep the number of neurons as 4 for eachlayer. During the training, you may find the training loss is oscillating, in this case, please continue the training by reducing the learning rate from 0.03 to 0.01 or even smaller to stabilize the training. Please train the model until the training loss become stable. Please try to explain the behavior.



                                              Table 2.1
Dataset |Loss |1 hidden layer |2 hidden layer |3 hidden layer 
------|-----|-----|-----|----- 
Square|Training|0.004|0.002|0.002
Square|Testing|0.032|0.010|0.017
Spiral|Training|0.313|0.300|0.161
Spiral|Testing|0.468|0.534|0.258

##### Observations (i)
Spiral data set has greater testing loss because of the complexity in the data form. Training loss is observed to be lower than testing loss. fluctuations or 'jitter' is observed because of step overshooting in locating the local optima, thus reducing the learning rate helps in reducing the step size and converge data at a steady rate. Jitter is observed in spiral data which is reduced by lowering the learning rate as mentioned in the problem statement. 

<br>

##### (ii) Width of network: First, please try to complete Table 2.2 by trying on selecting two out of four datasets with different neural networks to test the effect of different number of neurons. We will keep the models with 3 hidden layers. Please try to explain the behavior.


                                              Table 2.2
Dataset |Loss |2 neurons |4 neurons |8 neurons 
------|-----|-----|-----|----- 
Exclusive or|Training|0.005|0.004|0.013
Exclusive or|Testing|0.010|0.004|0.019
Spiral|Training|0.477|0.477|0.473
Spiral|Testing|0.473|0.475|0.473

##### Observations (ii)
Spiral data set has greater testing loss because of the complexity in the data form. Training loss is observed to be lower than testing loss. fluctuations or 'jitter' is observed because of step overshooting in locating the local optima, thus reducing the learning rate helps in reducing the step size and converge data at a steady rate. Jitter is observed in spiral data which is reduced by lowering the learning rate as mentioned in the problem statement.

<br>

### Problem 2
##### (i) Suppose P(snow today) = 0.30, P(snow tomorrow) = 0.60, P(snow today and tomorrow) = 0.25. Given that it snows today, what is the probability it will snow tomorrow? Please show brief steps for calculation 

Given: P(snow today) = P(A) = 0.30 ; P(snow tomorrow) = P(B) = 0.60 ; P(snow today and tomorrow) = P(AnB) = 0.25

P(B|A) = P(AnB) / P(A)  => P(B|A) = 0.25 / 0.30 = 0.83

<br>

##### (ii) What does it mean when a machine learning model is overfitting? Select the most appropriate explanation. Only the answer is needed.

Answer - (d) A model that is overfitting is a model that was trained on too much data

<br>

##### (iii) Which of the following can help resolve the overfitting issue? Only the answer is needed.

Answer - (b) Increase the number of training samples

<br>

### Problem 3
##### (A)  Please write a program that uses Numpy, creates two random 100 ×100 arrays A and B and add them together as C = A + B in two different ways: (i) By using the for-loop method to compute each element of C by Cij = Aij + Bij for all i,j = 1,··· ,100.

##### Please answer the following questions (a) Write a small program for both methods and test each methods 100 times and record the timing results in a numpy ector of length 100. (b) For each method, please compute the average and standard deviation of the running time. Please answer the following questions

METHOD 1 - using for-loop

In [28]:
import numpy as np
import time
def addition1():
    A = np.random.randint(10, 90, (100, 100))
    B = np.random.randint(10, 90, (100, 100))
    C = np.random.randint(0, 1, (100, 100))
    for i in range(100):
        for j in range(100):
            C[i][j] = A[i][j] + B[i][j]
    return C
print("Array after adding A & B using for loop method:\n")
print(addition1())
print()
%timeit addition1()
addition1MethodTimes = []
for i in range(100):
    startTime = time.time()
    addition1()
    endTime = time.time()
    addition1MethodTimes.append((endTime-startTime)*1000)
addition1MethodTimes = np.array(addition1MethodTimes)
print("\n\n Time for addition method: \n")
print(addition1MethodTimes)
print("\n\n Average time for addition: ")
print(addition1MethodTimes.mean())
print("\n\n Standard Deviation for addition: ")
print(addition1MethodTimes.std())

Array after adding A & B using for loop method:

[[154 132 129 ... 101  69 101]
 [140  74 110 ... 116 124  79]
 [122 106 126 ... 111 122  93]
 ...
 [ 97  94 132 ... 143 164 126]
 [ 90 114  82 ... 123 153  98]
 [106  95  70 ...  88  92 103]]

6.77 ms ± 20.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


 Time for addition method: 

[15.60664177  0.         15.62523842  0.          0.         15.62619209
  0.         20.96509933  0.         13.14616203  6.3393116   7.00163841
  7.00831413  4.98795509  0.          0.         15.64860344  0.
 15.62619209  0.         15.62619209  0.          0.         15.614748
  0.         15.63739777  0.         15.62643051  7.46822357  0.
  0.         20.86377144  7.00092316  7.11870193  0.          0.
 15.63811302  0.         18.21112633  7.2054863   0.         13.32569122
  7.22050667  0.89836121 12.59183884  6.54888153  2.10285187  0.
 15.63835144  0.         15.62619209  0.          0.         15.67721367
  0.         15.57469368  0.    

##### (ii) By using the numpy built-in function for matrix multiplication.

METHOD 2 - using numpy built-in function

In [27]:
import numpy as np
import time
def addition2():
    A = np.random.randint(10, 90, (100, 100))
    B = np.random.randint(10, 90, (100, 100))
    C = np.add(A,B)
    #C = A.__add__(B)
    return C
print("Array after adding A & B using numpy built-in function \n")
print(addition2())
print()
%timeit addition2()
addition2MethodTimes = []
for i in range(100):
    startTime = time.time()
    addition2()
    endTime = time.time()
    addition2MethodTimes.append((endTime-startTime)*1000)
addition2MethodTimes = np.array(addition2MethodTimes)
print("\n Time for addition2Matrix method using numpy: \n")
print(addition2MethodTimes)
print("\n Average time for addition2Matrix using numpy: ")
print(addition2MethodTimes.mean())
print("\n Standard Deviation for addition2Matrix numpy: ")
print(addition2MethodTimes.std())

Array after adding A & B using numpy built-in function 

[[ 98 133  75 ... 122  37 129]
 [101 127 111 ...  86 132  85]
 [142  88  72 ... 146  88  61]
 ...
 [150 139  93 ...  74  59  48]
 [109 115  66 ... 121  70 138]
 [ 70 117 129 ... 138 139 106]]

235 µs ± 2.64 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

 Time for addition2Matrix method using numpy: 

[ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.         15.65074921
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.        

<br>

##### (B)  Please write a program that uses Numpy, creates two random 100 ×100 arrays A and B and multiple them together as C = AB in two different ways: (i) By using the for-loop method to compute each element of C by Cij = ∑k AikBkj for all i,j = 1,···,100. 

##### Please answer the following questions (a) Write a small program for both methods and test each methods 100 times and record the timing results in a numpy ector of length 100. (b) For each method, please compute the average and standard deviation of the running time.Please answer the following questions

In [25]:
import numpy as np
import time
def multiplication1():
    A = np.random.randint(10, 90, (100, 100))
    B = np.random.randint(10, 90, (100, 100))
    C = np.random.randint(0, 1, (100, 100))
    for i in range(100):
        for j in range(100):
            C[i][j] = A[i][j] * B[i][j]
    return C
print("Array after multiplying A & B using for loop method: \n")
print(multiplication1())
print()
%timeit multiplication1()
import numpy as np
multiplication1MethodTimes = []
for i in range(100):
    startTime = time.time()
    multiplication1()
    endTime = time.time()
    multiplication1MethodTimes.append((endTime-startTime)*1000)
multiplication1MethodTimes = np.array(multiplication1MethodTimes)
print("\n\n Time for multiplication1 method using for loop: \n")
print(multiplication1MethodTimes)
print("\n Average time for multiplication1 for using for loop: ")
print(multiplication1MethodTimes.mean())
print("\n Standard Deviation for multiplication1 using for loop: ")
print(multiplication1MethodTimes.std())

Array after multiplying A & B using for loop method: 

[[6972  221 3526 ... 4698 4307 7476]
 [2378 1595  378 ... 5440 7568 1680]
 [ 576 6004 1800 ... 4624 3953 1512]
 ...
 [ 966 2052 3366 ... 6052 2400  276]
 [1584 2607 4400 ... 6640 1440 1664]
 [1311 4088 1122 ... 1495 2665  636]]

6.74 ms ± 61.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


 Time for multiplication1 method using for loop: 

[ 0.         15.6109333   0.         15.8905983   0.          0.
 15.75779915  0.         15.54107666  0.         15.32936096  0.
 15.62595367  0.          0.         15.62595367  0.         15.62595367
  0.         15.62666893  0.          0.         15.62523842  0.
 15.62738419  0.         15.62523842  0.          0.         15.62571526
  0.         18.35107803  2.89297104 10.51354408  6.99496269  4.60672379
  0.         15.64145088  0.          0.         15.62643051  0.
 15.62547684  0.         15.6276226   0.          0.         15.62476158
  0.         15.62595367  0.         15

(ii) By using the numpy built-in function for matrix multiplication

In [26]:
import numpy as np
import time
def multiplication2():
    A = np.random.randint(10, 90, (100, 100))
    B = np.random.randint(10, 90, (100, 100))
    C = np.matmul(A, B)
    return C
print("Array after multiplication of A & B using numpy library: \n")
print(multiplication2())
print()
%timeit multiplication2
multiplication2MethodTimes = []
for i in range(100):
    startTime = time.time()
    multiplication2()
    endTime = time.time()
    multiplication2MethodTimes.append((endTime-startTime)*1000)
multiplication2MethodTimes = np.array(multiplication2MethodTimes)
print("\n Time for multiplication2 of A & B using numpy library: \n")
print(multiplication2MethodTimes)
print("\n Average time for multiplication2 of A & B using numpy library: ")
print(multiplication2MethodTimes.mean())
print("\n Standard Deviation for multiplication2 A & B using numpy library: ")
print(multiplication2MethodTimes.std())

Array after multiplication of A & B using numpy library: 

[[233884 249593 243316 ... 243741 228500 242644]
 [239829 231021 240120 ... 239726 218799 242302]
 [254880 256903 267422 ... 254539 241618 266116]
 ...
 [246329 235362 236676 ... 230298 222459 244808]
 [236199 238445 241707 ... 232173 217437 235858]
 [262263 263255 263131 ... 249196 241025 260735]]

20.2 ns ± 0.188 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

 Time for multiplication2 of A & B using numpy library: 

[1.00016594 2.0005703  0.         1.00016594 1.00111961 1.0008812
 0.         0.99897385 0.99992752 1.00016594 1.00016594 0.
 1.00016594 1.0008812  1.00040436 1.00016594 0.         0.9996891
 1.00016594 1.00016594 0.         1.00016594 1.0008812  0.99992752
 1.00064278 0.         1.00064278 0.99945068 0.99992752 1.00183487
 0.         1.00398064 0.99611282 0.99921227 1.0035038  0.
 0.99897385 0.99873543 0.99992752 0.         1.20830536 0.99873543
 0.99825859 0.         1.00398064 0.99873543 0.99873